apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: writer
    image: nginx:alpine
    command: ["sh", "-c", "echo data-written-by-writer > /shared/msg.txt; sleep 300"]
    volumeMounts:
    - name: shared-vol
      mountPath: /shared
  - name: reader
    image: nginx:alpine
    command: ["sh", "-c", "sleep 3; cat /shared/msg.txt; sleep 300"]
    volumeMounts:
    - name: shared-vol
      mountPath: /shared
  volumes:
  - name: shared-vol
    emptyDir: {}          # lives & dies with the Pod
