apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: app
    image: nginx:alpine
    command: ["sh", "-c", "echo hello-from-pod > /node-data/pod-file.txt; sleep 300"]
    volumeMounts:
    - name: node-vol
      mountPath: /node-data
  volumes:
  - name: node-vol
    hostPath:
      path: /tmp/hostpath-demo     # directory on the NODE's filesystem
      type: DirectoryOrCreate
