apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
spec:
  replicas: 3
  strategy:
    type: Recreate                 # kill ALL old pods first, then create new
  selector:
    matchLabels:
      app: app-recreate
  template:
    metadata:
      labels:
        app: app-recreate
        version: v1
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
